spring:
  application:
    name: HappyHouse
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://127.0.0.1:3306/happyHouse
=======
    url: jdbc:mysql://127.0.0.1:3306/happyhouse
>>>>>>> 37fa727 (Update spring version)
    username: root
    password: pwd0127!!

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
<<<<<<< HEAD
      ddl-auto: update

external:
  google:
    key:
      "AIzaSyDmn5MgBYwWy8SL1iT-i-feOEs0TBH1i0s"
    geocoding:
      endpoint:
        "https://maps.googleapis.com/maps/api/geocode"
  data:
    key:
      "c%2FQ%2FWGhWs5NTNfSpvWGw7Xqp55J7XYR8YqwNORhLoY99x1twg%2FLGAaN8VK9WKsZCEcEclHkMKftaMwzMlNajWA%3D%3D"
    region-code:
      endpoint:
        "http://apis.data.go.kr/1741000/StanReginCd"
    apt-trade:
      endpoint:
        "http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev"
    house-trade:
      endpoint:
        "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcRHTrade"
=======
      ddl-auto: create
>>>>>>> 37fa727 (Update spring version)
